<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Exception in BurgerScriptnull]]>
    </line>
    <line>
      <![CDATA[VerifySignUp execution completed.]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="44117" started-at="2018-04-26T05:27:07Z" finished-at="2018-04-26T05:27:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="44117" started-at="2018-04-26T05:27:07Z" finished-at="2018-04-26T05:27:51Z">
      <class name="com.BurgerApp.LaunchScreenScripts.VerifySignUp">
        <test-method status="PASS" signature="startUp()[pri:0, instance:com.BurgerApp.LaunchScreenScripts.VerifySignUp@64bfbc86]" name="startUp" is-config="true" duration-ms="37155" started-at="2018-04-26T10:57:07Z" finished-at="2018-04-26T10:57:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startUp -->
        <test-method status="PASS" signature="beforeTest(java.lang.reflect.Method)[pri:0, instance:com.BurgerApp.LaunchScreenScripts.VerifySignUp@64bfbc86]" name="beforeTest" is-config="true" duration-ms="0" started-at="2018-04-26T10:57:44Z" finished-at="2018-04-26T10:57:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.BurgerApp.LaunchScreenScripts.VerifySignUp.HomeScreenValidations()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="HomeScreenValidations()[pri:0, instance:com.BurgerApp.LaunchScreenScripts.VerifySignUp@64bfbc86]" name="HomeScreenValidations" duration-ms="5560" started-at="2018-04-26T10:57:44Z" finished-at="2018-04-26T10:57:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.BurgerApp.LaunchScreenScripts.VerifySignUp.HomeScreenValidations(VerifySignUp.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Exception in BurgerScriptnull]]>
            </line>
          </reporter-output>
        </test-method> <!-- HomeScreenValidations -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.BurgerApp.LaunchScreenScripts.VerifySignUp@64bfbc86]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-04-26T10:57:50Z" finished-at="2018-04-26T10:57:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.BurgerApp.LaunchScreenScripts.VerifySignUp@64bfbc86]" name="tearDown" is-config="true" duration-ms="1388" started-at="2018-04-26T10:57:50Z" finished-at="2018-04-26T10:57:51Z">
          <reporter-output>
            <line>
              <![CDATA[VerifySignUp execution completed.]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.BurgerApp.LaunchScreenScripts.VerifySignUp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
